name: padelero
description: "Tu marcador de pÃ¡del inteligente."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.4
  share_plus: ^10.1.2
  audioplayers: ^6.1.0
  vibration: ^2.0.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.3.3
  in_app_purchase: ^3.2.3
  app_tracking_transparency: ^2.0.6
  url_launcher: ^6.2.5
  fl_chart: ^0.69.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/